apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: api-portal
  title: Portal as framework
  description: Create a full Backstage-based developer portal framework with frontend and backend
  tags:
    - api
    - portal
    - developer
    - rhdh
spec:
  owner: rhdh-team
  type: service

  parameters:
    - title: Framework Configuration
      required:
        - portalName
        - description
        - portalVisibility
        - owner
        - repoOwner
        - repoName
      properties:
        portalName:
          title: Portal name
          type: string
          description: The name of your Backstage framework portal
          ui:autofocus: true
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: A detailed description of your Backstage framework portal
          ui:widget: textarea
        portalVisibility:
          title: Portal visibility
          type: string
          description: Control who can access the portal
          enum:
            - Private
            - Public
          enumNames:
            - Private (Only authenticated users can access)
            - Public (Anyone can access)
          default: Private
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
              - User
        repoOwner:
          title: Repository Owner
          type: string
          description: GitHub username or organization name (e.g., my-org or my-username)
          ui:autofocus: false
        repoName:
          title: Repository Name
          type: string
          description: GitHub repository name (e.g., my-backstage-portal). Make sure this name doesn't already exist in your GitHub account.
          ui:autofocus: false
    - title: Frontend Configuration
      properties:
        enableHome:
          title: Home
          type: boolean
          description: Enable Home menu item
          default: true
        enableCatalog:
          title: Catalog
          type: boolean
          description: Enable Catalog menu item
          default: false
        enableApi:
          title: APIs
          type: boolean
          description: Enable APIs menu item
          default: true
        enableSearch:
          title: Search
          type: boolean
          description: Enable Search menu item
          default: false
        enableLearningPaths:
          title: Learning Paths
          type: boolean
          description: Enable Learning Paths menu item
          default: false
        enableSelfService:
          title: Self-service
          type: boolean
          description: Enable Self-service menu item
          default: false
    - title: Backend Configuration
      properties:
        enableTechDocs:
          title: Enable TechDocs
          type: boolean
          description: Enable TechDocs documentation support
          default: true
        enableKubernetes:
          title: Enable Kubernetes
          type: boolean
          description: Enable Kubernetes plugin support
          default: false
        enableGitHub:
          title: Enable GitHub Integration
          type: boolean
          description: Enable GitHub integration for catalog discovery
          default: false

  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: ./api-portal-skeleton
        values:
          portalName: ${{ parameters.portalName }}
          description: ${{ parameters.description }}
          # 使用 | string 确保 owner 被强制渲染为字符串
          owner: ${{ parameters.owner | string }}
          component_id: ${{ parameters.portalName }}
          repoOwner: ${{ parameters.repoOwner }}
          repoName: ${{ parameters.repoName }}
          enableHome: ${{ parameters.enableHome }}
          enableCatalog: ${{ parameters.enableCatalog }}
          enableApi: ${{ parameters.enableApi }}
          enableSearch: ${{ parameters.enableSearch }}
          enableLearningPaths: ${{ parameters.enableLearningPaths }}
          enableSelfService: ${{ parameters.enableSelfService }}
          enableTechDocs: ${{ parameters.enableTechDocs }}
          enableKubernetes: ${{ parameters.enableKubernetes }}
          enableGitHub: ${{ parameters.enableGitHub }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=${{ parameters.repoOwner }}&repo=${{ parameters.repoName }}
        defaultBranch: main
        repoVisibility: ${{ parameters.portalVisibility | lower }}
        sourcePath: .

    - id: register
      name: Register
      action: catalog:register
      input:
        # 强制使用 blob 格式，这是 GitHub 官方 API 注册实体的标准格式
        # 使用固定的 owner (Joeyyubo) 而不是用户输入的 repoOwner
        repoContentsUrl: https://github.com/Joeyyubo/${{ parameters.repoName }}/blob/main/catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}

