apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: planpolicies.extensions.kuadrant.io
spec:
  group: extensions.kuadrant.io
  names:
    kind: PlanPolicy
    listKind: PlanPolicyList
    plural: planpolicies
    singular: planpolicy
    shortNames:
    - pp
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - targetRef
            - plans
            properties:
              targetRef:
                type: object
                description: reference to the HTTPRoute or Gateway this policy applies to
                required:
                - kind
                - name
                properties:
                  group:
                    type: string
                    default: gateway.networking.k8s.io
                  kind:
                    type: string
                    enum: [HTTPRoute, Gateway]
                  name:
                    type: string
                  namespace:
                    type: string
              plans:
                type: array
                description: list of plan tiers with rate limits and predicates
                minItems: 1
                items:
                  type: object
                  required:
                  - tier
                  properties:
                    tier:
                      type: string
                      description: plan tier name (e.g. gold, silver, bronze)
                    predicate:
                      type: string
                      description: rego predicate expression for matching requests to this plan
                    limits:
                      type: object
                      description: rate limits for this plan tier
                      properties:
                        daily:
                          type: integer
                          description: daily request limit
                        weekly:
                          type: integer
                          description: weekly request limit
                        monthly:
                          type: integer
                          description: monthly request limit
                        custom:
                          type: array
                          description: custom rate limits
                          items:
                            type: object
                            required:
                            - limit
                            - window
                            properties:
                              limit:
                                type: integer
                              window:
                                type: string
                                pattern: ^([0-9]{1,5}(h|m|s|ms)){1,4}$
                    description:
                      type: string
                      description: human-readable description of this plan tier
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  required:
                  - type
                  - status
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
    additionalPrinterColumns:
    - name: Target Ref
      type: string
      jsonPath: .spec.targetRef.kind + "/" + .spec.targetRef.name
    - name: Plans
      type: string
      jsonPath: .spec.plans[*].tier
      description: Available plan tiers
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    subresources:
      status: {}
